### ISSUE TITLE
SendMessage race condition when Publishing

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/go-mod-messaging#27]
The ZMQ SendMessage method is not thread safe. When calling this method Publish, we must use a mutex. This is manifest it self in multiple ways. First was this issue https://github.com/edgexfoundry/edgex-go/issues/1512  in Export Distro. Additionally it causes Core Data to crash either in the C++ library or in the GO 0MQ package as this stack trace shows
``````2019-07-15T18:01:40.276841834Z level=INFO ts=2019-07-15T18:01:40.276727191Z app=edgex-core-data source=event.go:240 msg="Putting event on message queue"
2019-07-15T18:01:40.276869619Z level=INFO ts=2019-07-15T18:01:40.276766473Z app=edgex-core-data source=event.go:240 msg="Putting event on message queue"
2019-07-15T18:01:40.277256157Z fatal error: unexpected signal during runtime execution
2019-07-15T18:01:40.277279205Z fatal error: unexpected signal during runtime execution
2019-07-15T18:01:40.279370588Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x59 pc=0x7f462e34946a]
2019-07-15T18:01:40.279383539Z 
2019-07-15T18:01:40.279387709Z runtime stack:
2019-07-15T18:01:40.279712745Z runtime.throw(0xc8702c, 0x2a)
2019-07-15T18:01:40.279720001Z     /usr/local/go/src/runtime/panic.go:617 +0x72
2019-07-15T18:01:40.279723059Z runtime.sigpanic()
2019-07-15T18:01:40.279725844Z     /usr/local/go/src/runtime/signal_unix.go:374 +0x4a9
2019-07-15T18:01:40.279728636Z 
2019-07-15T18:01:40.279736899Z goroutine 24007 [syscall]:
2019-07-15T18:01:40.279740092Z runtime.cgocall(0xac14b0, 0xc000366ce8, 0xc000028770)
2019-07-15T18:01:40.279742826Z     /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000366cb8 sp=0xc000366c80 pc=0x40665b
2019-07-15T18:01:40.279760909Z github.com/pebbe/zmq4._C2func_zmq_send(0x7f462e17a740, 0xc000028770, 0x6, 0x2, 0x0, 0x0, 0x0)
2019-07-15T18:01:40.279776945Z     _cgo_gotypes.go:487 +0x55 fp=0xc000366ce8 sp=0xc000366cb8 pc=0x904c75
2019-07-15T18:01:40.279789559Z github.com/pebbe/zmq4.(*Socket).SendBytes.func1(0xc00044c090, 0xc000366d98, 0xc000028770, 0x6, 0x8, 0x2, 0xc000028770, 0xc00012a0b8, 0x6)
2019-07-15T18:01:40.279798832Z     /go/pkg/mod/github.com/pebbe/zmq4@v1.0.0/zmq4.go:998 +0x12d fp=0xc000366d48 sp=0xc000366ce8 pc=0x91018d
2019-07-15T18:01:40.279815441Z github.com/pebbe/zmq4.(*Socket).SendBytes(0xc00044c090, 0xc000028770, 0x6, 0x8, 0x2, 0x8, 0x280, 0x8)
2019-07-15T18:01:40.279823532Z     /go/pkg/mod/github.com/pebbe/zmq4@v1.0.0/zmq4.go:998 +0x8f fp=0xc000366dc0 sp=0xc000366d48 pc=0x90da7f
2019-07-15T18:01:40.279835711Z github.com/pebbe/zmq4.(*Socket).Send(...)
2019-07-15T18:01:40.279840333Z     /go/pkg/mod/github.com/pebbe/zmq4@v1.0.0/zmq4.go:982
2019-07-15T18:01:40.279854548Z github.com/pebbe/zmq4.(*Socket).sendMessage(0xc00044c090, 0x0, 0xc000366f00, 0x2, 0x2, 0x0, 0x0, 0xb3f620)
2019-07-15T18:01:40.279867252Z     /go/pkg/mod/github.com/pebbe/zmq4@v1.0.0/utils.go:82 +0x7b9 fp=0xc000366e98 sp=0xc000366dc0 pc=0x903689
2019-07-15T18:01:40.279975409Z github.com/pebbe/zmq4.(*Socket).SendMessage(...)
2019-07-15T18:01:40.279981557Z     /go/pkg/mod/github.com/pebbe/zmq4@v1.0.0/utils.go:18
2019-07-15T18:01:40.279986748Z github.com/edgexfoundry/go-mod-messaging/internal/pkg/zeromq.(*zeromqClient).Publish(0xc000250000, 0x0, 0x0, 0xc000524000, 0x24, 0xc0001c22c0, 0x15d, 0x160, 0xc759d2, 0x10, ...)```

Do the following to recreate this issue:

1. Run EdgeX using https://github.com/edgexfoundry/developer-scripts/blob/master/compose-files/docker-compose-edinburgh-no-secty-1.0.0.yml
2. From Consul set the core-data & export-distro logging levels to `TRACE`
3. Using a DB tool like Robo 3T, connect to the EdgeX Mongo instance and set the AutoEvents frequency to 500ms for all devices in the MetaData
4. Restart device-virtual using Run device-random natively with AutoEvents frequency to 500ms for all devices in the local configuration.toml

**Comment by lenny-intel** [comment]
Duplicate
