### ISSUE TITLE
Runtime panic when running unit-tests against go-mod-messaging module

### ISSUE THREAD

**Issue by judehung** [edgexfoundry/go-mod-messaging#92]
The current code base of master branch will encounter runtime panic, as shown below, when running `make test`:

Moreover, we shall also consider to apply DevOps process to this module, so any new code commits could be verified.

```
CGO_ENABLED=1 GO111MODULE=on go test ./... -coverprofile=coverage.out ./...
?   	github.com/edgexfoundry/go-mod-messaging/v2/internal/pkg	[no test files]
--- FAIL: TestClientCreatorTLS (0.00s)
    --- FAIL: TestClientCreatorTLS/Skip_TLS_Config_from_PEM_Block_for_non-supported_TLS_protocols (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6cbb0d]

goroutine 32 [running]:
testing.tRunner.func1.1(0x7071c0, 0x963b00)
	/usr/local/go/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000153b00)
	/usr/local/go/src/testing/testing.go:1075 +0x41a
panic(0x7071c0, 0x963b00)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/edgexfoundry/go-mod-messaging/v2/internal/pkg/mqtt.TestClientCreatorTLS.func1(0xc000153b00)
	/home/judehung/MyDev/DevRepos/EdgeX/go-mod-messaging/internal/pkg/mqtt/client_test.go:444 +0x1ad
testing.tRunner(0xc000153b00, 0xc00004b650)
	/usr/local/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1168 +0x2b3
FAIL	github.com/edgexfoundry/go-mod-messaging/v2/internal/pkg/mqtt	0.009s
ok  	github.com/edgexfoundry/go-mod-messaging/v2/internal/pkg/redis/streams	0.014s	coverage: 77.1% of statements
?   	github.com/edgexfoundry/go-mod-messaging/v2/internal/pkg/redis/streams/mocks	[no test files]
--- FAIL: TestPublish (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5d78d6]

goroutine 8 [running]:
testing.tRunner.func1.1(0x60d6c0, 0x98bc50)
	/usr/local/go/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc0000da300)
	/usr/local/go/src/testing/testing.go:1075 +0x41a
panic(0x60d6c0, 0x98bc50)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:74
github.com/edgexfoundry/go-mod-messaging/v2/internal/pkg/zeromq.(*zeromqClient).bindToPort(0xc0000a3180, 0xc000018b60, 0xc, 0x0, 0x0)
	/home/judehung/MyDev/DevRepos/EdgeX/go-mod-messaging/internal/pkg/zeromq/client.go:235 +0x56
github.com/edgexfoundry/go-mod-messaging/v2/internal/pkg/zeromq.(*zeromqClient).Publish(0xc0000a3180, 0x0, 0x0, 0x646052, 0x3, 0xc000018b40, 0xa, 0xa, 0x0, 0x0, ...)
	/home/judehung/MyDev/DevRepos/EdgeX/go-mod-messaging/internal/pkg/zeromq/client.go:70 +0x268
github.com/edgexfoundry/go-mod-messaging/v2/internal/pkg/zeromq.TestPublish(0xc0000da300)
	/home/judehung/MyDev/DevRepos/EdgeX/go-mod-messaging/internal/pkg/zeromq/client_test.go:112 +0x125
testing.tRunner(0xc0000da300, 0x65a8f8)
	/usr/local/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1168 +0x2b3
FAIL	github.com/edgexfoundry/go-mod-messaging/v2/internal/pkg/zeromq	0.006s
ok  	github.com/edgexfoundry/go-mod-messaging/v2/messaging	0.003s	coverage: 85.7% of statements
ok  	github.com/edgexfoundry/go-mod-messaging/v2/messaging/mqtt	0.003s	coverage: 100.0% of statements
ok  	github.com/edgexfoundry/go-mod-messaging/v2/messaging/redis	0.003s	coverage: 100.0% of statements
ok  	github.com/edgexfoundry/go-mod-messaging/v2/pkg/types	0.004s	coverage: 90.9% of statements
FAIL
Makefile:6: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by lenny-intel** [comment]
These changes did pass Verify checks. Unit tests passed.
https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fgo-mod-messaging/detail/PR-91/2/pipeline

This is very strange. After I rebase my `master` and run unit tests I am again getting original failure, but not the panic shown here. :-(

investigating ....

**Comment by lenny-intel** [comment]
After redoing my fork to ensure my code is actuate for master branch, my unit tests failures are resolved and can not reproduce this  `panic` issue.

**Comment by lenny-intel** [comment]
@jim-wang-intel was able to reproduce panic on his Linux system and we root caused it to code that should have always panic.

The strange thing is this should have caused panic on my Widows system and in the CI verify job, but didn't. :-(
